### PR TITLE
Translation of the names of new items

### PR DESCRIPTION
**Pull request by Eldrinn-Elantey**

### CODE REVIEW

**Review by Dream-Master — APPROVED** [review]

**Comment by Eldrinn-Elantey** [comment]
I saw that the emerald cistern was replaced with an aluminum one, but the recipe remained the same with emeralds, is this normal?

**Comment by Dream-Master** [comment]
it got only a different name and a new material. Emerald as material make no sense (ok diamond also)

**Comment by Eldrinn-Elantey** [comment]
> it got only a different name and a new material. Emerald as material make no sense (ok diamond also)

I got it. I mean that in 2.1.0.0 the name and texture are new, and the recipe is old

**Comment by Dream-Master** [comment]
no recipe must be new also

**Pull request merged**
